name: catt-bff

on:
  workflow_dispatch:
  pull_request:
    paths: [ catt_bff/** ]
  push:
    branches: [ main ]
    paths: [ catt_bff/** ]

jobs:
  wrangler-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: catt_bff/package-lock.json

      - name: Install dependencies
        working-directory: catt_bff
        run: npm ci

      - name: Run tests
        working-directory: catt_bff
        run: npm test

      - name: Dry run deploy
        if: github.event_name == 'pull_request'
        working-directory: catt_bff
        run: npx wrangler deploy --dry-run
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      # - name: Deploy
      #   if: github.event_name != 'pull_request'
      #   working-directory: catt_bff
      #   run: npx wrangler deploy
      #   env:
      #     CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
